import type { InferSelectModel } from "drizzle-orm";
import { marketMonthlyReturns, marketMonthlyReturnLines } from "@shared/db-schema";

type ReturnRow = InferSelectModel<typeof marketMonthlyReturns>;
type LineRow = InferSelectModel<typeof marketMonthlyReturnLines>;

export async function buildMarketReturnPdf(params: {
  ret: ReturnRow;
  lines: LineRow[];
  yardLabel: string;
  traderLabel: string;
}): Promise<Buffer> {
  const { ret, lines, yardLabel, traderLabel } = params;
  const { default: PDFDocument } = await import("pdfkit");

  const doc = new PDFDocument({ margin: 48, size: "A4" });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));

  await new Promise<void>((resolve, reject) => {
    doc.on("end", () => resolve());
    doc.on("error", reject);

    doc.fontSize(16).text("GAPLMB — Market Fee Monthly Return", { align: "center" });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#555").text("Integrated Online Management System (IOMS)", { align: "center" });
    doc.fillColor("#000");
    doc.moveDown(1);

    doc.fontSize(11).text(`Location: ${yardLabel}`);
    doc.text(`Trader: ${traderLabel}`);
    doc.text(`Period: ${ret.period}`);
    if (ret.acknowledgementRef) doc.text(`Acknowledgement ref: ${ret.acknowledgementRef}`);
    doc.text(`Status: ${ret.status}`);
    if (ret.submittedAt) doc.text(`Submitted at: ${String(ret.submittedAt).slice(0, 19).replace("T", " ")}`);
    doc.moveDown(0.8);

    doc.fontSize(11).text("Summary (INR)", { underline: true });
    doc.fontSize(10);
    doc.text(`Total purchase value: ₹${Number(ret.totalPurchaseValueInr ?? 0).toFixed(2)}`);
    doc.text(`Market fee (computed): ₹${Number(ret.totalMarketFeeInr ?? 0).toFixed(2)}`);
    if (ret.deadlineDate) doc.text(`Deadline: ${ret.deadlineDate}`);
    if (Number(ret.daysLate ?? 0) > 0) {
      doc
        .fillColor("#b45309")
        .text(`Late submission: Yes (${Number(ret.daysLate)} day(s))`);
      doc.fillColor("#000");
      doc.text(`Interest on market fee: ₹${Number(ret.interestAmountInr ?? 0).toFixed(2)}`);
    } else {
      doc.text("Late submission: No");
    }
    doc.moveDown(0.8);

    doc.fontSize(11).text("Commodity lines", { underline: true });
    doc.moveDown(0.4);

    // Simple table layout (fixed columns)
    const startX = doc.x;
    const col = {
      commodity: startX,
      opening: startX + 160,
      purchaseQty: startX + 230,
      purchaseVal: startX + 310,
      sales: startX + 410,
      closing: startX + 470,
    };
    doc.fontSize(9).fillColor("#222");
    doc.text("Commodity", col.commodity, doc.y, { width: 155 });
    doc.text("Open", col.opening, doc.y, { width: 50, align: "right" });
    doc.text("Buy", col.purchaseQty, doc.y, { width: 60, align: "right" });
    doc.text("Value", col.purchaseVal, doc.y, { width: 90, align: "right" });
    doc.text("Sales", col.sales, doc.y, { width: 55, align: "right" });
    doc.text("Close", col.closing, doc.y, { width: 55, align: "right" });
    doc.fillColor("#000");
    doc.moveDown(0.3);
    doc.moveTo(startX, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).strokeColor("#ddd").stroke();
    doc.moveDown(0.2);

    doc.strokeColor("#000");
    for (const l of lines) {
      const rowY = doc.y;
      doc.fontSize(9).text(String(l.commodityId ?? ""), col.commodity, rowY, { width: 155 });
      doc.text(String(Number(l.openingQty ?? 0)), col.opening, rowY, { width: 50, align: "right" });
      doc.text(String(Number(l.purchaseQty ?? 0)), col.purchaseQty, rowY, { width: 60, align: "right" });
      doc.text(`₹${Number(l.purchaseValueInr ?? 0).toFixed(2)}`, col.purchaseVal, rowY, { width: 90, align: "right" });
      doc.text(String(Number(l.salesQty ?? 0)), col.sales, rowY, { width: 55, align: "right" });
      doc.text(String(Number(l.closingQty ?? 0)), col.closing, rowY, { width: 55, align: "right" });
      doc.moveDown(0.6);
      if (doc.y > doc.page.height - doc.page.margins.bottom - 60) {
        doc.addPage();
      }
    }

    doc.moveDown(1);
    doc.fontSize(8).fillColor("#666").text("Generated by IOMS. This PDF is a system-generated acknowledgement for record purposes.", {
      align: "center",
    });
    doc.end();
  });

  return Buffer.concat(chunks);
}

