/**
 * M-05: server-generated receipt PDF — GAPLMB statutory layout (A4 duplicate slips).
 * Logo optional via Admin Config / RECEIPT_PDF_LOGO_* (letterhead is text unless preprinted mode).
 */
import QRCode from "qrcode";
import type { InferSelectModel } from "drizzle-orm";
import { iomsReceipts } from "@shared/db-schema";
import { loadPdfDocumentConstructor } from "./pdfkit-loader";
import { pdfSafeText } from "./pdf-safe-text";
import { loadReceiptPdfLayoutContext } from "./receipt-pdf-context";
import { drawGaplmbReceiptSlip } from "./receipt-pdf-layout";
import { readUploadedReceiptLogoBuffer } from "./receipt-logo-storage";

type ReceiptRow = InferSelectModel<typeof iomsReceipts>;

export type ReceiptPdfArrearsDisclosure = {
  approxInterestInr: number;
  overdueDays: number;
  dueDateIso: string;
  asOfIso: string;
  ratePercentPerAnnum: number;
  principalInr: number;
  note: string;
};

const A4_MARGIN = 36;
/** Two slips + gap must stay above bottom margin on A4 (~842pt). */
const SLIP_HEIGHT = 364;
const SLIP_GAP = 8;
const FIRST_SLIP_Y = 36;
const SECOND_SLIP_Y = FIRST_SLIP_Y + SLIP_HEIGHT + SLIP_GAP;

export async function buildIomsReceiptPdf(params: {
  receipt: ReceiptRow;
  yardName?: string | null;
  verifyBaseUrl: string;
  arrearsDisclosure?: ReceiptPdfArrearsDisclosure | null;
  duplicateLabel?: string | null;
}): Promise<Buffer> {
  const { receipt, verifyBaseUrl, arrearsDisclosure, duplicateLabel } = params;
  const printMode = (process.env.RECEIPT_PDF_PRINT_MODE ?? "full").trim().toLowerCase();
  const bodyOnly = printMode === "body-only" || printMode === "preprinted";
  const signatoryName = process.env.RECEIPT_PDF_SIGNATORY_NAME?.trim();

  let layoutCtx = await loadReceiptPdfLayoutContext(receipt);
  if (arrearsDisclosure && arrearsDisclosure.approxInterestInr > 0.005) {
    layoutCtx = {
      ...layoutCtx,
      remarks: `${layoutCtx.remarks} (Prior dishonour: approx. arrears interest ${arrearsDisclosure.approxInterestInr.toFixed(2)} INR — not in total above.)`,
    };
  }

  const PDFDocument = await loadPdfDocumentConstructor().catch((e) => {
    console.error("[receipt-pdf] pdfkit module load failed", e);
    throw e;
  });

  const verifyUrl = `${verifyBaseUrl.replace(/\/$/, "")}/verify/${encodeURIComponent(receipt.receiptNo)}`;
  let qrPng: Buffer | null = null;
  try {
    qrPng = await QRCode.toBuffer(verifyUrl, { type: "png", margin: 1, width: 160 });
  } catch (e) {
    console.warn("[receipt-pdf] QR generation failed", e);
  }

  const logoPng = bodyOnly ? null : await readUploadedReceiptLogoBuffer();

  const doc = new PDFDocument({ size: "A4", margin: A4_MARGIN });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));

  await new Promise<void>((resolve, reject) => {
    doc.on("end", () => resolve());
    doc.on("error", reject);

    if (duplicateLabel) {
      doc
        .save()
        .rotate(-18, { origin: [doc.page.width / 2, doc.page.height / 2] })
        .fontSize(44)
        .fillColor("#d1d5db")
        .opacity(0.35)
        .text(pdfSafeText(String(duplicateLabel).slice(0, 40)), 0, doc.page.height / 2 - 40, { align: "center" })
        .opacity(1)
        .restore();
    }

    const leftX = doc.page.margins.left;
    const rightX = doc.page.width - doc.page.margins.right;
    const contentWidth = rightX - leftX;
    const slipOpts = {
      bodyOnly,
      signatoryName: signatoryName || null,
      logoPng,
      qrPng: bodyOnly ? null : qrPng,
      verifyUrl: bodyOnly ? null : verifyUrl,
    };

    drawGaplmbReceiptSlip(
      doc,
      layoutCtx,
      { x: leftX, y: FIRST_SLIP_Y, width: contentWidth, height: SLIP_HEIGHT },
      slipOpts,
    );
    drawGaplmbReceiptSlip(
      doc,
      layoutCtx,
      { x: leftX, y: SECOND_SLIP_Y, width: contentWidth, height: SLIP_HEIGHT },
      slipOpts,
    );

    doc
      .font("Helvetica")
      .fontSize(7)
      .fillColor("#666")
      .text(
        pdfSafeText("Duplicate copy on the same A4 sheet for office / lessee use. Generated by IOMS."),
        leftX,
        doc.page.height - doc.page.margins.bottom - 14,
        { width: contentWidth, align: "center" },
      );
    doc.fillColor("#000");
    doc.end();
  });

  return Buffer.concat(chunks);
}
