/**
 * Dump all gapmc schema table data to db_table_backup.sql as INSERT statements.
 * Requires DATABASE_URL in .env. Run: npm run db:backup-data
 */
import "dotenv/config";
import { Pool } from "pg";
import * as fs from "fs";
import * as path from "path";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("DATABASE_URL is not set. Add it to .env");
  process.exit(1);
}

const pool = new Pool({ connectionString, statement_timeout: 0 });

function escapeSqlValue(val: unknown): string {
  if (val === null || val === undefined) return "NULL";
  if (typeof val === "boolean") return val ? "true" : "false";
  if (typeof val === "number" && !Number.isNaN(val)) return String(val);
  if (Buffer.isBuffer(val)) return "'" + val.toString("hex").replace(/'/g, "''") + "'";
  if (typeof val === "object") return "'" + String(JSON.stringify(val)).replace(/'/g, "''") + "'";
  return "'" + String(val).replace(/'/g, "''") + "'";
}

function quoteIdent(name: string): string {
  return '"' + name.replace(/"/g, '""') + '"';
}

async function main() {
  const outPath = path.join(process.cwd(), "db_table_backup.sql");
  const stream = fs.createWriteStream(outPath, { encoding: "utf8" });
  const write = (s: string) =>
    new Promise<void>((resolve, reject) => {
      stream.write(s, (err) => (err ? reject(err) : resolve()));
    });

  await write("-- GAPMC table data backup (INSERT statements)\n");
  await write("-- Schema: gapmc. Generated by scripts/dump-db-data.ts\n");
  await write(`-- Generated: ${new Date().toISOString()}\n\n`);
  await write("BEGIN;\n\n");

  const client = await pool.connect();
  try {
    await client.query("SET statement_timeout = 0");
    await client.query("SET idle_in_transaction_session_timeout = 0");

    const tablesResult = await client.query(
      `SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'gapmc' AND table_type = 'BASE TABLE'
       ORDER BY table_name`
    );
    const tables = tablesResult.rows.map((r: { table_name: string }) => r.table_name);
    console.log(`Dumping ${tables.length} tables…`);

    for (const table of tables) {
      const colsResult = await client.query(
        `SELECT column_name FROM information_schema.columns
         WHERE table_schema = 'gapmc' AND table_name = $1
         ORDER BY ordinal_position`,
        [table]
      );
      const columns = colsResult.rows.map((r: { column_name: string }) => r.column_name);
      const quotedCols = columns.map(quoteIdent).join(", ");
      const tableRef = `gapmc.${quoteIdent(table)}`;

      const res = await client.query(`SELECT * FROM ${tableRef}`);
      const rows = res.rows as Record<string, unknown>[];

      if (rows.length === 0) {
        await write(`-- Table gapmc.${table}: 0 rows\n\n`);
        process.stdout.write(".");
        continue;
      }

      const rowLabel = rows.length === 1 ? "row" : "rows";
      await write(`-- Table gapmc.${table}: ${rows.length} ${rowLabel}\n`);
      for (const row of rows) {
        const values = columns.map((col) => escapeSqlValue(row[col]));
        await write(`INSERT INTO ${tableRef} (${quotedCols}) VALUES (${values.join(", ")});\n`);
      }
      await write("\n");
      console.log(`  ${table}: ${rows.length}`);
    }

    await write("COMMIT;\n\n");
    await new Promise<void>((resolve, reject) => {
      stream.end(() => resolve());
      stream.on("error", reject);
    });
    console.log("Written:", outPath);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
