/**
 * Dump all gapmc schema table data to db_table_backup.sql as INSERT statements.
 * Requires DATABASE_URL in .env. Run: npm run db:backup-data (or dotenv -e .env -- tsx scripts/dump-db-data.ts)
 */
import "dotenv/config";
import { Pool } from "pg";
import * as fs from "fs";
import * as path from "path";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("DATABASE_URL is not set. Add it to .env");
  process.exit(1);
}

const pool = new Pool({ connectionString });

function escapeSqlValue(val: unknown): string {
  if (val === null || val === undefined) return "NULL";
  if (typeof val === "boolean") return val ? "true" : "false";
  if (typeof val === "number" && !Number.isNaN(val)) return String(val);
  if (typeof val === "object") return "'" + String(JSON.stringify(val)).replace(/'/g, "''") + "'";
  return "'" + String(val).replace(/'/g, "''") + "'";
}

function quoteIdent(name: string): string {
  return '"' + name.replace(/"/g, '""') + '"';
}

async function main() {
  const outPath = path.join(process.cwd(), "db_table_backup.sql");
  const lines: string[] = [
    "-- GAPMC table data backup (INSERT statements)",
    "-- Schema: gapmc. Generated by scripts/dump-db-data.ts",
    `-- Generated: ${new Date().toISOString()}`,
    "",
    "BEGIN;",
    "",
  ];

  const client = await pool.connect();
  try {
    const tablesResult = await client.query(
      `SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'gapmc'
       ORDER BY table_name`
    );
    const tables = tablesResult.rows.map((r: { table_name: string }) => r.table_name);

    for (const table of tables) {
      const colsResult = await client.query(
        `SELECT column_name FROM information_schema.columns
         WHERE table_schema = 'gapmc' AND table_name = $1
         ORDER BY ordinal_position`,
        [table]
      );
      const columns = colsResult.rows.map((r: { column_name: string }) => r.column_name);
      const quotedCols = columns.map(quoteIdent).join(", ");
      const tableRef = `gapmc.${quoteIdent(table)}`;

      const res = await client.query(`SELECT * FROM ${tableRef}`);
      const rows = res.rows as Record<string, unknown>[];

      if (rows.length === 0) {
        lines.push(`-- Table gapmc.${table}: 0 rows`);
        lines.push("");
        continue;
      }

      const rowLabel = rows.length === 1 ? "row" : "rows";
      lines.push(`-- Table gapmc.${table}: ${rows.length} ${rowLabel}`);
      for (const row of rows) {
        const values = columns.map((col) => escapeSqlValue(row[col]));
        const valueList = values.join(", ");
        lines.push("INSERT INTO " + tableRef + " (" + quotedCols + ") VALUES (" + valueList + ");");
      }
      lines.push("");
    }

    lines.push("COMMIT;");
    lines.push("");
    fs.writeFileSync(outPath, lines.join("\n"), "utf8");
    console.log("Written:", outPath);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
